/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

import java.util.LinkedHashSet;

public class App {
    public static void main(String[] args) {

        //LinkedHashSet<garagem> = new LinkedHashSet<>();
    }
}
